import LaptopCard from "@/components/ui/LaptopCard";
import { TLaptop } from "@/types";
import { Metadata } from "next";
import React from "react";

export const metadata: Metadata = {
  title: "My-Gadget | All Laptop",
  description: "Generated by create next app",
};
const LaptopPage = async () => {
  const res = await fetch("http://localhost:5000/laptop/", {
    cache: "no-store",
  });
  const allLaptop = await res.json();

  return (
    <div className=" my-4">
      <div className=" my-4">
        <h1 className="text-4xl text-accent text-center my-4 border-y-2 border-emerald-400 w-[25%]  py-2 mx-auto ">
          All Laptop
        </h1>
        <p className="w-2/4 mx-auto">
          On the other hand, students or casual users might find joy in a more
          affordable
        </p>
      </div>

      <div className="md:grid grid-cols-3 gap-8">
        {allLaptop.map((laptop: TLaptop) => (
          <LaptopCard key={laptop._id} laptop={laptop} />
        ))}
      </div>
    </div>
  );
};

export default LaptopPage;
