import { Metadata } from "next";

export const metadata: Metadata = {
  title: "My-Gadget | Dashboard ",
  description: "Generated by create next app",
};

const DashboardPage = () => {
  return (
    <div className="my-4">
      <h1 className="text-3xl text-green-600 text-center">
        {" "}
        Welcome to Dashboard Section
      </h1>
    </div>
  );
};

export default DashboardPage;
