import { Metadata } from "next";
import React from "react";

export const metadata: Metadata = {
  title: "My-Gadget | Contact Us",
  description: "Generated by create next app",
};
const ContactUsPage = () => {
  return (
    <div className="my-8 border border-emerald-400 p-4  shadow-md shadow-emerald-200">
      <p className="text-4xl text-green-500 ">Head Office</p>
      <p>My Gadget Limited Tokyo Bhaban</p>
      <p>Begum Rokeya Sharani, Agargaon, Dhaka-1207</p>
      <p>01717000000</p>
      <p>01918000000</p>
    </div>
  );
};

export default ContactUsPage;
